language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to run tests
script:
    - pip install biopython planemo
    - python script.py test-data/seq.fa P
    - planemo test --conda_dependency_resolution script.xml
